
server:
  port: 8080

spring:
  datasource:
    # 데이터베이스 연결 정보 (필요 시 주석 해제하여 사용)
    # url: jdbc:postgresql://localhost:5432/your_db_name
    # username: your_username
    # password: your_password
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true # DB의 snake_case를 Java의 camelCase로 자동 매핑